Algoritmo "ava05"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 5/30/2023
Var
   // Seção de Declarações das variáveis
   x,y:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   enquanto (x<=10)faca
      escreva(x)
      enquanto (y<=5) faca
         escreva(y)
         y<-y+1
      fimenquanto
      y<-1
      x<-x+1
   fimenquanto

Fimalgoritmo