Algoritmo "mesesDoAno"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 5/29/2023
Var
// Seção de Declarações das variáveis 
   mes:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite o número do mês: ")
   leia(mes)
   escolha(mes)
   caso 1
        escreval("Mês de janeiro!")


Fimalgoritmo