Algoritmo "sorteiro60"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 5/30/2023
Var
   // Seção de Declarações das variáveis
   num: real
   x: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   x<-0
   enquanto (x<6) faca
      num<- Randi(60)
      escreva (num)
      x<-x+1
   fimenquanto
Fimalgoritmo